.TH "Referencia del directorio srclib" 3 "Miércoles, 20 de Abril de 2016" "Practica 2 - Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio srclib \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBG-2301-01-P1-daemon\&.c\fP"
.br
.RI "\fILibreria de creacion de un daemon\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P1-tcp\&.c\fP"
.br
.RI "\fILibreria de manejo de sockets TCP\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P1-tools\&.c\fP"
.br
.RI "\fILibreria de utilidades\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P1-udp\&.c\fP"
.br
.RI "\fILibreria de manejo de sockets UDP\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P2-ccomm\&.c\fP"
.br
.RI "\fILibreria de manejo de mensajes IRC\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P2-rtp\&.c\fP"
.br
.RI "\fILibreria de manejo de paquetes RTP\&. \fP"
.ti -1c
.RI "archivo \fBG-2301-01-P2-ucomm\&.c\fP"
.br
.RI "\fILibreria de manejo de comandos de usuario\&. \fP"
.in -1c
