.TH "Referencia del directorio src" 3 "Miércoles, 20 de Abril de 2016" "Practica 2 - Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio src \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBxchat2\&.c\fP"
.br
.RI "\fIPrograma principal del cliente IRC\&. \fP"
.in -1c
