.TH "_thread_file" 3 "Miércoles, 20 de Abril de 2016" "Practica 2 - Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_thread_file \- 
.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 
Definición en la línea 1132 del archivo xchat2\&.c\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica 2 - Redes de Comunicaciones II del código fuente\&.
