.TH "srclib/G-2301-01-P1-udp.c" 3 "Miércoles, 20 de Abril de 2016" "Practica 2 - Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srclib/G-2301-01-P1-udp.c \- 
.PP
Libreria de manejo de sockets UDP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <G-2301-01-P1-udp\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBserver_udpsocket_open\fP (uint16_t port, int *socketd)"
.br
.RI "\fIAbre un socket UDP para servidor\&. \fP"
.ti -1c
.RI "int \fBclient_udpsocket_open\fP (uint16_t port, int *socketd)"
.br
.RI "\fIAbre un socket UDP para cliente\&. \fP"
.ti -1c
.RI "int \fBudpsocket_snd\fP (int socketd, char *dst, uint16_t port, void *data, size_t len)"
.br
.RI "\fIEnvia los datos a traves del socket UDP\&. \fP"
.ti -1c
.RI "int \fBudpsocket_rcv\fP (int socketd, char *src, uint16_t port, void *data, size_t max, size_t *len)"
.br
.RI "\fIRecibe a traves del socket UDP\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Libreria de manejo de sockets UDP\&. 


.PP
\fBAutor:\fP
.RS 4
Sergio Fuentes sergio.fuentesd@estudiante.uam.es 
.PP
Daniel Perdices daniel.perdices@estudiante.uam.es 
.RE
.PP
\fBFecha:\fP
.RS 4
2016/04/16 
.RE
.PP

.PP
Definición en el archivo \fBG-2301-01-P1-udp\&.c\fP\&.
.SH "Documentación de las funciones"
.PP 
.SS "int client_udpsocket_open (uint16_tport, int *socketd)"

.PP
Abre un socket UDP para cliente\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIport\fP Puerto desde el que se desea escuchar 
.br
\fIsocketd\fP Puntero al descriptor del socket 
.RE
.PP
\fBDevuelve:\fP
.RS 4
UDPOK si todo fue correcto UDPERR_ARGS/SOCKET en caso de error con estas funciones 
.RE
.PP

.PP
Definición en la línea 58 del archivo G-2301-01-P1-udp\&.c\&.
.SS "int server_udpsocket_open (uint16_tport, int *socketd)"

.PP
Abre un socket UDP para servidor\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIport\fP Puerto desde el que se desea escuchar 
.br
\fIsocketd\fP Puntero al descriptor del socket 
.RE
.PP
\fBDevuelve:\fP
.RS 4
UDPOK si todo funciono correctamente UDPERR_ARGS/SOCKET/BIND en caso de error con estas funciones 
.RE
.PP

.PP
Definición en la línea 25 del archivo G-2301-01-P1-udp\&.c\&.
.SS "int udpsocket_rcv (intsocketd, char *src, uint16_tport, void *data, size_tmax, size_t *len)"

.PP
Recibe a traves del socket UDP\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsocketd\fP Descriptor del socket escuchado 
.br
\fIsrc\fP direccion INET de origen 
.br
\fIport\fP puerto INET de origen 
.br
\fIdata\fP puntero a donde se almacenan los datos 
.br
\fImax\fP tamaño de la zona de memoria 
.br
\fIlen\fP puntero a la variable de longitud recibida 
.RE
.PP
\fBDevuelve:\fP
.RS 4
UDPOK si todo fue correcto UDPERR_ARGS/RECV en caso de error con estas funciones 
.RE
.PP

.PP
Definición en la línea 120 del archivo G-2301-01-P1-udp\&.c\&.
.SS "int udpsocket_snd (intsocketd, char *dst, uint16_tport, void *data, size_tlen)"

.PP
Envia los datos a traves del socket UDP\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsocketd\fP Descriptor del socket escuchado 
.br
\fIdst\fP direccion INET de destino 
.br
\fIport\fP puerto INET de destino 
.br
\fIdata\fP puntero a los datos que se han de enviar 
.br
\fIlen\fP tamano de los datos a enviar 
.RE
.PP
\fBDevuelve:\fP
.RS 4
UDPOK si todo fue correcto UDPERR_ARGS/SEND en caso de error con estas funciones 
.RE
.PP

.PP
Definición en la línea 81 del archivo G-2301-01-P1-udp\&.c\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica 2 - Redes de Comunicaciones II del código fuente\&.
